from fastapi import APIRouter, UploadFile, File, HTTPException, Form
from pydantic import BaseModel
from utils.mime_detector import detect_mime_type
from pipelines.image_pipeline import run as run_image_pipeline
import uuid
import logging
from routes.common import enforce_size, IMAGE_TYPES

logger = logging.getLogger(__name__)
router = APIRouter()

class VisionResponse(BaseModel):
    job_id:   str
    answer:   str
    model:    str
    prompt:   str
    filename: str

@router.post(
    "/vision",
    response_model=VisionResponse,
    summary="Image-to-text via Kimi-K2.5 (moonshotai)",
    description=(
        "Upload any supported image (PNG, JPEG, WEBP, GIF) with an optional text prompt. "
        "Returns a natural-language answer generated by moonshotai/Kimi-K2.5."
    ),
)
async def vision_endpoint(
    file:    UploadFile = File(..., description="Image file (PNG / JPEG / WEBP / GIF)"),
    message: str        = Form(
        default="Describe this image in detail.",
        description="Question or instruction for the vision model.",
    ),
) -> VisionResponse:
    content = await file.read()
    mime = detect_mime_type(content, file.content_type)

    if mime not in IMAGE_TYPES:
        raise HTTPException(
            status_code=415,
            detail=f"Expected an image file. Got MIME type: '{mime}'. "
                   f"Accepted: {sorted(IMAGE_TYPES)}",
        )

    enforce_size(content, "image")

    job_id = str(uuid.uuid4())
    logger.info("[%s] /vision called | file=%s | mime=%s | prompt='%s'",
                job_id, file.filename, mime, message[:80])

    try:
        result = await run_image_pipeline(
            job_id=job_id,
            content=content,
            mime=mime,
            message=message,
        )
    except Exception as exc:
        logger.exception("[%s] Vision pipeline error", job_id)
        raise HTTPException(status_code=500, detail=f"Vision model error: {exc}")

    return VisionResponse(
        job_id=result.job_id,
        answer=result.answer,
        model=result.model,
        prompt=result.prompt,
        filename=file.filename,
    )
